### ISSUE TITLE
How to use this in Unit Test (plain unit test)?

### ISSUE THREAD

**Issue by parkiyong** [arcao/slf4j-timber#7]
When I use it in plain unit test (in android app project), it always give me:

```
java.lang.RuntimeException: Method isEmpty in android.text.TextUtils not mocked. See http://g.co/androidstudio/not-mocked for details.

	at android.text.TextUtils.isEmpty(TextUtils.java)
	at timber.log.Timber$Tree.prepareLog(Timber.java:527)
	at timber.log.Timber$Tree.d(Timber.java:418)
	at timber.log.Timber$1.d(Timber.java:240)
	at timber.log.Timber.d(Timber.java:35)
```
and I'm not even using **android.text.TextUtils**

**Comment by arcao** [comment]
Use [Roboelectric](http://robolectric.org/).
